---
- name: "[bind] configuration (options)"
  action: template src={{ item }} dest={{ dns_bind_chroot }}/conf.d/00_server.cfg backup=no owner={{ dns_bind_user }}  group={{ dns_bind_group }} mode=0640
  first_available_file:
    - "{{ dns_dir_prefix }}/bind9/bind_cfg_options.{{ inventory_hostname }}.j2"
    - "{{ dns_dir_prefix }}/bind9/bind_cfg_options.default.j2"
  tags:
    - dns
    - bind
    - config
  notify:
    - "[bind9] combine config"

- name: "[bind] configuration (acl)"
  action: template src={{ item }} dest={{ dns_bind_chroot }}/conf.d/10_acl.cfg backup=no owner={{ dns_bind_user }}  group={{ dns_bind_group }} mode=0640
  first_available_file:
    - "{{ dns_dir_prefix }}/bind9/bind_cfg_acl.{{ inventory_hostname }}.j2"
    - "{{ dns_dir_prefix }}/bind9/bind_cfg_acl.default.j2"
  tags:
    - dns
    - bind
    - config
  notify:
    - "[bind9] combine config" 

- name: "[bind] configuration (key)"
  action: template src={{ dns_dir_prefix }}/bind9/bind_cfg_key.{{ item.name }}.j2 dest={{ dns_bind_chroot }}/conf.d/20_key_{{ item.name }}.cfg owner={{ dns_bind_user }}  group={{ dns_bind_group }} mode=0640
  tags:
    - dns
    - bind
    - config
  with_items: dns_keys_tsig
  when: "item.state == 'enabled'"
  notify:
    - "[bind9] combine config"

- name: "[bind] configuration remove (key)"
  action: file path={{ dns_bind_chroot }}/conf.d/20_key_{{ item.name }}.cfg state=absent
  tags:
    - dns
    - bind
    - config
  with_items: dns_keys_tsig
  when: "item.state != 'enabled'"
  notify:
    - "[bind9] combine config"

- name: "[bind] configuration (zones)"
  action: template src={{ dns_dir_prefix }}/bind9/bind_cfg_zone.{{ item.template }}.j2 dest={{ dns_bind_chroot }}/conf.d/30_zone.{{ item.zone }}.cfg owner={{ dns_bind_user }} group={{ dns_bind_group }} mode=0640
  tags:
    - dns
    - bind
    - config
  with_items: dns_zones
  when: "item.state == 'enabled'"
  notify:
    - "[bind9] combine config"

- name: "[bind] configuration remove (zones)"
  action: file path={{ dns_bind_chroot }}/conf.d/30_zone.{{ item.zone }}.cfg state=absent
  tags:
    - dns
    - bind
    - config
  with_items: dns_zones
  when: "item.state != 'enabled'"
  notify:
    - "[bind9] combine config"
