---
- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - dns
    - nsd
    - bind
    - knot
    - setup
    - config
    - service

- include: bind9-setup-Debian.yml
  when: "'dns-bind9' in {{ group_names }} and ansible_os_family == 'Debian'"
- include: bind9-setup-RedHat.yml
  when: "'dns-bind9' in {{ group_names }} and ansible_os_family == 'RedHat'"
- include: bind9-setup-common.yml
  when: "'dns-bind9' in {{ group_names }}"
- include: bind9-config.yml
  when: "'dns-bind9' in {{ group_names }}"
- include: bind9-service.yml
  when: "'dns-bind9' in {{ group_names }}"

- include: nsd3-setup-Debian.yml
  when: "'dns-nsd3' in {{ group_names }} and ansible_os_family == 'Debian'"
- include: nsd3-setup-RedHat.yml
  when: "'dns-nsd3' in {{ group_names }} and ansible_os_family == 'RedHat'"
- include: nsd3-setup-common.yml
  when: "'dns-nsd3' in {{ group_names }}"
- include: nsd3-config.yml
  when: "'dns-nsd3' in {{ group_names }}"
- include: nsd3-service.yml
  when: "'dns-nsd3' in {{ group_names }}"

- include: knot-setup-Debian.yml
  when: "'dns-knot' in {{ group_names }} and ansible_os_family == 'Debian'"
- include: knot-setup-RedHat.yml
  when: "'dns-knot' in {{ group_names }} and ansible_os_family == 'RedHat'"
- include: knot-setup-common.yml
  when: "'dns-knot' in {{ group_names }}"
- include: knot-config.yml
  when: "'dns-knot' in {{ group_names }}"
- include: knot-service.yml
  when: "'dns-knot' in {{ group_names }}"
